#!/bin/bash
# Export a fine-tuned Zipformer checkpoint to ONNX for sherpa-onnx deployment.
#
# Usage:
#   bash export_to_onnx.sh [standard|kroko] [epoch_num]
#
# ⚠️  The exact export script path and argument names must be verified on the pod
#     by inspecting the Icefall clone after setup_pod.sh runs.
#
set -euo pipefail

VARIANT="${1:-standard}"
EPOCH="${2:-1}"
ICEFALL_DIR="/workspace/finetune/icefall"
EXP_DIR="/workspace/finetune/exp/${VARIANT}"
ONNX_DIR="/workspace/finetune/onnx/${VARIANT}"
WEIGHTS_DIR="/workspace/finetune/weights/${VARIANT}"

mkdir -p "${ONNX_DIR}"

echo "============================================"
echo "  Export ${VARIANT} epoch-${EPOCH} → ONNX"
echo "  Source:  ${EXP_DIR}/epoch-${EPOCH}.pt"
echo "  Output:  ${ONNX_DIR}"
echo "============================================"

cd "${ICEFALL_DIR}"

# ── Discover available export scripts ──
echo ""
echo "=== Available export scripts ==="
find egs/librispeech/ASR -name "*export*onnx*" -o -name "*onnx*export*" 2>/dev/null
echo ""

# ── Verify checkpoint exists ──
if [ ! -f "${EXP_DIR}/epoch-${EPOCH}.pt" ]; then
    echo "ERROR: Checkpoint not found: ${EXP_DIR}/epoch-${EPOCH}.pt"
    echo "       Available checkpoints:"
    ls "${EXP_DIR}/"*.pt 2>/dev/null || echo "       (none found)"
    exit 1
fi

# ── Export ──
# Streaming Zipformer needs chunk_size and left_context to match inference.
# Values below match what sherpa_zipformer/model.py uses (chunk_size=16, left_context=128).
# Icefall export scripts commonly use:
#   --exp-dir, --epoch, --avg, --chunk-size, --left-context-frames, --output-dir
#
# ⚠️  Update the script name and arguments after finding the real export script above.

EXPORT_SCRIPT="egs/librispeech/ASR/zipformer/export-onnx-streaming.py"
if [ ! -f "${EXPORT_SCRIPT}" ]; then
    # Try alternative names
    for candidate in \
        "egs/librispeech/ASR/zipformer/export_onnx_streaming.py" \
        "egs/librispeech/ASR/zipformer/export-onnx.py" \
        "egs/librispeech/ASR/zipformer/export.py"; do
        if [ -f "${candidate}" ]; then
            EXPORT_SCRIPT="${candidate}"
            break
        fi
    done
fi

if [ ! -f "${EXPORT_SCRIPT}" ]; then
    echo "ERROR: ONNX export script not found."
    echo "       Search: find ${ICEFALL_DIR}/egs -name '*onnx*' -o -name '*export*'"
    echo "       Run that search on the pod and update this script."
    exit 1
fi

echo "=== Using export script: ${EXPORT_SCRIPT} ==="
python3 "${EXPORT_SCRIPT}" \
    --exp-dir "${EXP_DIR}" \
    --epoch "${EPOCH}" \
    --avg 1 \
    --chunk-size 16 \
    --left-context-frames 128 \
    --output-dir "${ONNX_DIR}" \
    2>&1 | tee "${EXP_DIR}/export.log"

# ── Copy tokenizer files ──
echo ""
echo "=== Copying tokenizer files ==="

BPE_SRC="${WEIGHTS_DIR}/data/lang_bpe_500/bpe.model"
if [ -f "${BPE_SRC}" ]; then
    cp "${BPE_SRC}" "${ONNX_DIR}/"
    echo "  Copied: bpe.model"
else
    echo "  WARNING: bpe.model not found at ${BPE_SRC}"
    echo "           tokens.txt (generated by export script) may be sufficient"
fi

# ── Rename ONNX files to standard names if needed ──
# sherpa_zipformer/model.py expects: encoder.onnx, decoder.onnx, joiner.onnx
for component in encoder decoder joiner; do
    # Find the actual output file (may have epoch/chunk suffix)
    actual=$(ls "${ONNX_DIR}/${component}"*.onnx 2>/dev/null | head -1 || true)
    expected="${ONNX_DIR}/${component}.onnx"
    if [ -n "${actual}" ] && [ "${actual}" != "${expected}" ]; then
        cp "${actual}" "${expected}"
        echo "  Copied: $(basename ${actual}) → ${component}.onnx"
    fi
done

echo ""
echo "============================================"
echo "  Export complete!"
echo "  Files in ${ONNX_DIR}:"
ls -lh "${ONNX_DIR}/" 2>/dev/null || true
echo ""
echo "  Next: run the quick validation in setup_pod.sh"
echo "        or: python3 evaluate_finetuned.py --onnx-dir ${ONNX_DIR} ..."
echo "============================================"
